---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.yellow.com
  resources:
  - grafanascalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.yellow.com
  resources:
  - grafanascalers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.yellow.com
  resources:
  - grafanascalers/status
  verbs:
  - get
  - patch
  - update
