// SPDX-License-Identifier: MIT
pragma solidity 0.8.18;

import '../Seeding.sol';

contract TESTSeeding is Seeding {
	/**
	 * @notice Event emitted when a seed is generated.
	 * @dev Event emitted when a seed is generated.
	 * @param seed Seed generated by Random contract.
	 */
	event SeedGenerated(bytes32 seed);

	/**
	 * @notice Creates a new seed based on the salt, pepper, nonce, sender address, and block timestamp. Emits SeedGenerated event.
	 * @dev Expose internal _randomSeed function.
	 */
	function randomSeed() external {
		emit SeedGenerated(_randomSeed());
	}
}
