// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: clear_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClearStream is aggregated message about status of the clearing protocol
// instance, including the nitro channel portfolio and settlement statuses
type ClearStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string      `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Positions []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *ClearStream) Reset() {
	*x = ClearStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clear_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearStream) ProtoMessage() {}

func (x *ClearStream) ProtoReflect() protoreflect.Message {
	mi := &file_clear_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearStream.ProtoReflect.Descriptor instead.
func (*ClearStream) Descriptor() ([]byte, []int) {
	return file_clear_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ClearStream) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ClearStream) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_clear_stream_proto protoreflect.FileDescriptor

var file_clear_stream_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x1a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a,
	0x0a, 0x0b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2d, 0x33,
	0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clear_stream_proto_rawDescOnce sync.Once
	file_clear_stream_proto_rawDescData = file_clear_stream_proto_rawDesc
)

func file_clear_stream_proto_rawDescGZIP() []byte {
	file_clear_stream_proto_rawDescOnce.Do(func() {
		file_clear_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_clear_stream_proto_rawDescData)
	})
	return file_clear_stream_proto_rawDescData
}

var file_clear_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clear_stream_proto_goTypes = []interface{}{
	(*ClearStream)(nil), // 0: clear_stream.ClearStream
	(*Position)(nil),    // 1: core.Position
}
var file_clear_stream_proto_depIdxs = []int32{
	1, // 0: clear_stream.ClearStream.positions:type_name -> core.Position
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clear_stream_proto_init() }
func file_clear_stream_proto_init() {
	if File_clear_stream_proto != nil {
		return
	}
	file_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_clear_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clear_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clear_stream_proto_goTypes,
		DependencyIndexes: file_clear_stream_proto_depIdxs,
		MessageInfos:      file_clear_stream_proto_msgTypes,
	}.Build()
	File_clear_stream_proto = out.File
	file_clear_stream_proto_rawDesc = nil
	file_clear_stream_proto_goTypes = nil
	file_clear_stream_proto_depIdxs = nil
}
