// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: exit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_ERC721      AssetType = 1
	AssetType_ASSET_TYPE_ERC1155     AssetType = 2
	AssetType_ASSET_TYPE_QUALIFIED   AssetType = 3
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_ERC721",
		2: "ASSET_TYPE_ERC1155",
		3: "ASSET_TYPE_QUALIFIED",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_ERC721":      1,
		"ASSET_TYPE_ERC1155":     2,
		"ASSET_TYPE_QUALIFIED":   3,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_exit_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_exit_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_exit_proto_rawDescGZIP(), []int{0}
}

type AllocationType int32

const (
	AllocationType_ALLOCATION_TYPE_UNSPECIFIED     AllocationType = 0
	AllocationType_ALLOCATION_TYPE_WITHDRAW_HELPER AllocationType = 1
	AllocationType_ALLOCATION_TYPE_GUARANTEE       AllocationType = 2
)

// Enum value maps for AllocationType.
var (
	AllocationType_name = map[int32]string{
		0: "ALLOCATION_TYPE_UNSPECIFIED",
		1: "ALLOCATION_TYPE_WITHDRAW_HELPER",
		2: "ALLOCATION_TYPE_GUARANTEE",
	}
	AllocationType_value = map[string]int32{
		"ALLOCATION_TYPE_UNSPECIFIED":     0,
		"ALLOCATION_TYPE_WITHDRAW_HELPER": 1,
		"ALLOCATION_TYPE_GUARANTEE":       2,
	}
)

func (x AllocationType) Enum() *AllocationType {
	p := new(AllocationType)
	*p = x
	return p
}

func (x AllocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_exit_proto_enumTypes[1].Descriptor()
}

func (AllocationType) Type() protoreflect.EnumType {
	return &file_exit_proto_enumTypes[1]
}

func (x AllocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllocationType.Descriptor instead.
func (AllocationType) EnumDescriptor() ([]byte, []int) {
	return file_exit_proto_rawDescGZIP(), []int{1}
}

type Allocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination    []byte         `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"` // bytes32 in solidity
	Amount         string         `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`           // big.Int cast to string
	AllocationType AllocationType `protobuf:"varint,3,opt,name=allocation_type,json=allocationType,proto3,enum=outcome.AllocationType" json:"allocation_type,omitempty"`
	Metadata       []byte         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Allocation) Reset() {
	*x = Allocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Allocation) ProtoMessage() {}

func (x *Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_exit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Allocation.ProtoReflect.Descriptor instead.
func (*Allocation) Descriptor() ([]byte, []int) {
	return file_exit_proto_rawDescGZIP(), []int{0}
}

func (x *Allocation) GetDestination() []byte {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Allocation) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Allocation) GetAllocationType() AllocationType {
	if x != nil {
		return x.AllocationType
	}
	return AllocationType_ALLOCATION_TYPE_UNSPECIFIED
}

func (x *Allocation) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AssetMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetType AssetType `protobuf:"varint,1,opt,name=asset_type,json=assetType,proto3,enum=outcome.AssetType" json:"asset_type,omitempty"`
	Metadata  []byte    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *AssetMetadata) Reset() {
	*x = AssetMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetMetadata) ProtoMessage() {}

func (x *AssetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_exit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetMetadata.ProtoReflect.Descriptor instead.
func (*AssetMetadata) Descriptor() ([]byte, []int) {
	return file_exit_proto_rawDescGZIP(), []int{1}
}

func (x *AssetMetadata) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *AssetMetadata) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SingleAssetExit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Either the zero address (implying the native token)
	// or the address of an ERC20 contract
	Asset         *Address       `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	AssetMetadata *AssetMetadata `protobuf:"bytes,2,opt,name=asset_metadata,json=assetMetadata,proto3" json:"asset_metadata,omitempty"`
	Allocations   []*Allocation  `protobuf:"bytes,3,rep,name=allocations,proto3" json:"allocations,omitempty"`
}

func (x *SingleAssetExit) Reset() {
	*x = SingleAssetExit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleAssetExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleAssetExit) ProtoMessage() {}

func (x *SingleAssetExit) ProtoReflect() protoreflect.Message {
	mi := &file_exit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleAssetExit.ProtoReflect.Descriptor instead.
func (*SingleAssetExit) Descriptor() ([]byte, []int) {
	return file_exit_proto_rawDescGZIP(), []int{2}
}

func (x *SingleAssetExit) GetAsset() *Address {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *SingleAssetExit) GetAssetMetadata() *AssetMetadata {
	if x != nil {
		return x.AssetMetadata
	}
	return nil
}

func (x *SingleAssetExit) GetAllocations() []*Allocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

type Exit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SingleAssetExits []*SingleAssetExit `protobuf:"bytes,1,rep,name=single_asset_exits,json=singleAssetExits,proto3" json:"single_asset_exits,omitempty"`
}

func (x *Exit) Reset() {
	*x = Exit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_exit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_exit_proto_rawDescGZIP(), []int{3}
}

func (x *Exit) GetSingleAssetExits() []*SingleAssetExit {
	if x != nil {
		return x.SingleAssetExits
	}
	return nil
}

var File_exit_proto protoreflect.FileDescriptor

var file_exit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x78, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x1a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0f, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5e, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x0a, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xac, 0x01, 0x0a, 0x0f, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x45, 0x78, 0x69, 0x74, 0x12, 0x23, 0x0a, 0x05,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x12, 0x3d, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x35, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x2e,
	0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a, 0x04, 0x45, 0x78, 0x69, 0x74, 0x12,
	0x46, 0x0a, 0x12, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x65, 0x78, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x45, 0x78, 0x69, 0x74, 0x52, 0x10, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x45, 0x78, 0x69, 0x74, 0x73, 0x2a, 0x70, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x15, 0x0a, 0x11, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45,
	0x52, 0x43, 0x37, 0x32, 0x31, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x53, 0x53, 0x45, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x52, 0x43, 0x31, 0x31, 0x35, 0x35, 0x10, 0x02, 0x12,
	0x18, 0x0a, 0x14, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x51, 0x55,
	0x41, 0x4c, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x75, 0x0a, 0x0e, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x41,
	0x4c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f,
	0x41, 0x4c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x57, 0x49, 0x54, 0x48, 0x44, 0x52, 0x41, 0x57, 0x5f, 0x48, 0x45, 0x4c, 0x50, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x4c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x55, 0x41, 0x52, 0x41, 0x4e, 0x54, 0x45, 0x45, 0x10, 0x02,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2d, 0x33, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exit_proto_rawDescOnce sync.Once
	file_exit_proto_rawDescData = file_exit_proto_rawDesc
)

func file_exit_proto_rawDescGZIP() []byte {
	file_exit_proto_rawDescOnce.Do(func() {
		file_exit_proto_rawDescData = protoimpl.X.CompressGZIP(file_exit_proto_rawDescData)
	})
	return file_exit_proto_rawDescData
}

var file_exit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_exit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_exit_proto_goTypes = []interface{}{
	(AssetType)(0),          // 0: outcome.AssetType
	(AllocationType)(0),     // 1: outcome.AllocationType
	(*Allocation)(nil),      // 2: outcome.Allocation
	(*AssetMetadata)(nil),   // 3: outcome.AssetMetadata
	(*SingleAssetExit)(nil), // 4: outcome.SingleAssetExit
	(*Exit)(nil),            // 5: outcome.Exit
	(*Address)(nil),         // 6: core.Address
}
var file_exit_proto_depIdxs = []int32{
	1, // 0: outcome.Allocation.allocation_type:type_name -> outcome.AllocationType
	0, // 1: outcome.AssetMetadata.asset_type:type_name -> outcome.AssetType
	6, // 2: outcome.SingleAssetExit.asset:type_name -> core.Address
	3, // 3: outcome.SingleAssetExit.asset_metadata:type_name -> outcome.AssetMetadata
	2, // 4: outcome.SingleAssetExit.allocations:type_name -> outcome.Allocation
	4, // 5: outcome.Exit.single_asset_exits:type_name -> outcome.SingleAssetExit
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_exit_proto_init() }
func file_exit_proto_init() {
	if File_exit_proto != nil {
		return
	}
	file_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_exit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Allocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleAssetExit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exit_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exit_proto_goTypes,
		DependencyIndexes: file_exit_proto_depIdxs,
		EnumInfos:         file_exit_proto_enumTypes,
		MessageInfos:      file_exit_proto_msgTypes,
	}.Build()
	File_exit_proto = out.File
	file_exit_proto_rawDesc = nil
	file_exit_proto_goTypes = nil
	file_exit_proto_depIdxs = nil
}
